name: Audit des dépendances
on:
  push:
    branches:
      - main
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Audit Node.js
        run: |
          pnpm install
          pnpm audit
      - name: Audit Python
        run: |
          pip install --upgrade pip
          pip install -r ai_services/requirements.txt
          pip install -r backend/requirements.txt
          pip install bandit
          bandit -r ai_services
          bandit -r backend
