name: Audit des dépendances
on:
  push:
    branches:
      - main
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Audit Node.js
        run: |
          pnpm install
          pnpm audit
      - name: Audit Python
        run: |
          pip install --upgrade pip
          # Install faiss-cpu first with binary wheel to avoid compilation issues
          pip install --only-binary=faiss-cpu faiss-cpu==1.11.0
          # Install other dependencies, excluding faiss-cpu, preferring binary wheels
          grep -v "faiss-cpu" ai_services/requirements.txt > temp_requirements.txt
          pip install --prefer-binary -r temp_requirements.txt
          pip install --prefer-binary -r backend/requirements.txt
          pip install bandit
          bandit -r ai_services
          bandit -r backend
